### ISSUE TITLE
Arbeiten mit XML-Korpora

### ISSUE THREAD

**Issue by johlei** [thvitt/corpuschars#7]
Als Editionswissenschaftler*in
will ich ein Korpus an TEI-XML-Dateien einlesen
um sie anschließend mit einer gegebenen Schriftart online dazustellen. Dazu muss ich zunächst das Korpus einlesen.

**Comment by eickelpasch** [comment]
Denk an die von uns getroffene Entscheidung, utf-8 codierte character vorauszusetzen.

**Comment by johlei** [comment]
Funktionalität ist mit den letzten beiden Commits erreicht!
